import type { WorkspaceSpec } from "./spec";

// NORTH — executive intelligence. The metric definition is the unit of work
// (docs/03 §NORTH): every other tab is that definition measured (snapshots,
// anomalies), narrated (briefings, board packs) or acted on (scenarios,
// decisions). Nothing here writes a module's hot tables.

export const north: WorkspaceSpec = {
  path: "/north",
  labels: {
    en: {
      "boardpacks.approve": "Approve",
      "boardpacks.approve.confirm": "Sign this pack off as final? It can then be sent to the board.",
      "boardpacks.distribute": "Send to the board",
      recipients: "Recipients (emails, comma separated)",
      metrics: "Metrics",
      snapshots: "Snapshots",
      briefings: "Briefings",
      anomalies: "Anomalies",
      alerts: "Alerts & thresholds",
      scenarios: "Scenarios",
      boardpacks: "Board packs",
      decisions: "Decisions",

      "link.brief": "The Brief",
      "link.metric": "Open the trend",
      "thresholdValue.hint": "In the metric's own units — minor units for money, basis points for a ratio.",
      "link.explorer": "Explorer",
      "link.anomalies": "Anomalies",
      "link.alerts": "Alert rules",
      "link.whatif": "What-if",
      "link.board": "Board pack",
    "link.decisions": "Decisions",
    "link.admin": "Insight admin",
    "link.dev": "Insight dev",
      "link.health": "Data health",
      "link.semantic": "Semantic model",
      "link.usage": "Adoption & cost",
      "link.dashboards": "Dashboards",
      "link.reports": "Reports & delivery",

      operator: "Fires when",
      thresholdValue: "Threshold",
      windowGrain: "Measured over",
      notifyChannelRef: "Notify",
      enabled: "Live",
      gt: "Above",
      gte: "At or above",
      lt: "Below",
      lte: "At or below",
      eq: "Exactly",
      driverAnalysisJson: "Reading",

      key: "Key",
      nameJson: "Name",
      definitionSqlRef: "Definition",
      unit: "Unit",
      currency: "Currency",
      grain: "Grain",
      owner: "Owner",
      targetJson: "Target",
      sensitivity: "Sensitivity",
      direction: "Good direction",
      metricKey: "Metric",
      metricName: "Metric",
      period: "Period",
      value: "Value",
      dimsHash: "Dimensions",
      ts: "As at",
      date: "Date",
      audience: "Audience",
      locale: "Language",
      status: "Status",
      narrativeRef: "Narrative",
      highlightsJson: "Highlights",
      anomaliesJson: "Anomalies cited",
      aiAuditId: "AI audit record",
      generatedBy: "Generated by",
      approvedBy: "Approved by",
      publishedAt: "Published",
      window: "Window",
      magnitude: "Deviation",
      expected: "Expected",
      actual: "Actual",
      state: "State",
      linkedActionRef: "Linked action",
      explainedBy: "Explained by",
      detectedAt: "Detected",
      question: "Question",
      assumptionsJson: "Assumptions",
      resultJson: "Result",
      modelRunRef: "Model run",
      author: "Author",
      sharedWithJson: "Shared with",
      title: "Title",
      sectionsJson: "Sections",
      pdfFileId: "PDF",
      xlsxFileId: "Spreadsheet",
      distributionLogJson: "Delivery log",
      chosen: "Chosen option",
      contextRef: "Context",
      optionsJson: "Options",
      reviewAt: "Review due",
      outcomeReviewJson: "Outcome review",

      count: "Count",
      money: "Money",
      percent: "Percent",
      ratio: "Ratio",
      duration_ms: "Duration",
      day: "Daily",
      week: "Weekly",
      month: "Monthly",
      public: "Public",
      internal: "Internal",
      restricted: "Restricted",
      up: "Up is good",
      down: "Down is good",
      exec: "Executive",
      board: "Board",
      investor: "Investor",
      draft: "Draft",
      review: "In review",
      published: "Published",
      new: "New",
      explained: "Explained",
      action_created: "Action created",
      dismissed: "Dismissed",
      final: "Final",
      distributed: "Distributed",
      open: "Open",
      reviewed: "Reviewed",
      reversed: "Reversed"
    },
    ar: {
      "boardpacks.approve": "اعتماد",
      "boardpacks.approve.confirm": "اعتماد هذه الحزمة نهائية؟ يمكن بعدها إرسالها إلى المجلس.",
      "boardpacks.distribute": "إرسال إلى المجلس",
      recipients: "المستلمون (عناوين بريد مفصولة بفواصل)",
      metrics: "المؤشرات",
      snapshots: "اللقطات",
      briefings: "الإحاطات",
      anomalies: "الانحرافات",
      alerts: "التنبيهات والحدود",
      scenarios: "السيناريوهات",
      boardpacks: "حزم مجلس الإدارة",
      decisions: "القرارات",

      "link.brief": "الموجز",
      "link.metric": "فتح المنحنى",
      "thresholdValue.hint": "بوحدات المؤشر نفسه — الوحدات الصغرى للمبالغ، ونقاط الأساس للنسب.",
      "link.explorer": "المستكشف",
      "link.anomalies": "الحالات الشاذة",
      "link.alerts": "قواعد التنبيه",
      "link.whatif": "ماذا لو",
      "link.board": "حزمة مجلس الإدارة",
    "link.decisions": "القرارات",
    "link.admin": "إدارة التحليلات التنفيذية",
    "link.dev": "مطوّرو التحليلات التنفيذية",
      "link.health": "سلامة البيانات",
      "link.semantic": "النموذج الدلالي",
      "link.usage": "الاستخدام والتكلفة",
      "link.dashboards": "لوحات المعلومات",
      "link.reports": "التقارير والتسليم",

      operator: "يُفعَّل عندما",
      thresholdValue: "الحد",
      windowGrain: "يُقاس على",
      notifyChannelRef: "إشعار إلى",
      enabled: "مُفعَّل",
      gt: "أعلى من",
      gte: "يساوي أو أعلى من",
      lt: "أقل من",
      lte: "يساوي أو أقل من",
      eq: "يساوي تمامًا",
      driverAnalysisJson: "القراءة",

      key: "المفتاح",
      nameJson: "الاسم",
      definitionSqlRef: "مرجع التعريف",
      unit: "الوحدة",
      currency: "العملة",
      grain: "التفصيل الزمني",
      owner: "المسؤول",
      targetJson: "المستهدف",
      sensitivity: "الحساسية",
      direction: "الاتجاه المرغوب",
      metricKey: "المؤشر",
      metricName: "المؤشر",
      period: "الفترة",
      value: "القيمة",
      dimsHash: "الأبعاد",
      ts: "بتاريخ",
      date: "التاريخ",
      audience: "الجمهور",
      locale: "اللغة",
      status: "الحالة",
      narrativeRef: "السرد",
      highlightsJson: "أبرز النقاط",
      anomaliesJson: "الانحرافات المذكورة",
      aiAuditId: "سجل تدقيق الذكاء الاصطناعي",
      generatedBy: "أُنشئ بواسطة",
      approvedBy: "اعتمده",
      publishedAt: "تاريخ النشر",
      window: "النافذة الزمنية",
      magnitude: "حجم الانحراف",
      expected: "المتوقع",
      actual: "الفعلي",
      state: "الوضع",
      linkedActionRef: "الإجراء المرتبط",
      explainedBy: "فسّره",
      detectedAt: "تاريخ الاكتشاف",
      question: "السؤال",
      assumptionsJson: "الافتراضات",
      resultJson: "النتيجة",
      modelRunRef: "تشغيل النموذج",
      author: "المؤلف",
      sharedWithJson: "تمت المشاركة مع",
      title: "العنوان",
      sectionsJson: "الأقسام",
      pdfFileId: "ملف PDF",
      xlsxFileId: "ملف جدول البيانات",
      distributionLogJson: "سجل التوزيع",
      chosen: "الخيار المعتمد",
      contextRef: "مرجع السياق",
      optionsJson: "الخيارات",
      reviewAt: "موعد المراجعة",
      outcomeReviewJson: "مراجعة النتيجة",

      count: "عدد",
      money: "مبلغ",
      percent: "نسبة مئوية",
      ratio: "نسبة",
      duration_ms: "مدة",
      day: "يومي",
      week: "أسبوعي",
      month: "شهري",
      public: "عام",
      internal: "داخلي",
      restricted: "مقيّد",
      up: "الارتفاع أفضل",
      down: "الانخفاض أفضل",
      exec: "الإدارة التنفيذية",
      board: "مجلس الإدارة",
      investor: "المستثمرون",
      draft: "مسودة",
      review: "قيد المراجعة",
      published: "منشور",
      new: "جديد",
      explained: "مُفسَّر",
      action_created: "تم إنشاء إجراء",
      dismissed: "مُستبعد",
      final: "نهائي",
      distributed: "تم التوزيع",
      open: "مفتوح",
      reviewed: "تمت المراجعة",
      reversed: "تم التراجع"
    }
  },
  tabs: [
    {
      key: "metrics",
      api: "/v1/north/metrics",
      read: "north:metrics:read",
      create: "north:metrics:write",
      update: "north:metrics:write",
      remove: "north:metrics:write",
      sort: "key",
      order: "asc",
      filters: [
        { name: "grain", options: ["day", "week", "month"] },
        { name: "unit", options: ["count", "money", "percent", "ratio", "duration_ms"] },
        { name: "sensitivity", options: ["public", "internal", "restricted"] }
      ],
      // The catalogue exists to settle disagreements between two screens, so the
      // definition and its owner are columns, not fields you must open a record
      // to read (docs/25 north_metrics).
      // ponytail: no bespoke metric screen exists; the generic record route
      // (/north/metrics/{id}) already shows definition and owner, so the row
      // opens there rather than at a 404.
      columns: [
        { name: "key", type: "text", sortable: true },
        { name: "definitionSqlRef", type: "text" },
        { name: "unit", type: "text" },
        { name: "grain", type: "text" },
        { name: "direction", type: "text" },
        { name: "sensitivity", type: "text", badge: true },
        { name: "owner", type: "text" },
        { name: "updatedAt", type: "datetime", sortable: true }
      ],
      fields: [
        { name: "key", type: "text", required: true },
        { name: "nameJson", type: "json", required: true },
        { name: "definitionSqlRef", type: "text", required: true },
        {
          name: "unit",
          type: "select",
          options: ["count", "money", "percent", "ratio", "duration_ms"]
        },
        { name: "currency", type: "text" },
        { name: "grain", type: "select", options: ["day", "week", "month"] },
        { name: "direction", type: "select", options: ["up", "down"] },
        { name: "sensitivity", type: "select", options: ["public", "internal", "restricted"] },
        { name: "owner", type: "text" },
        { name: "targetJson", type: "json" }
      ],
      // `key` is the semantic layer's identity — snapshots, anomalies and every
      // dashboard reference it by name, so it is set once and never edited.
      editable: [
        { name: "nameJson", type: "json" },
        { name: "definitionSqlRef", type: "text" },
        { name: "direction", type: "select", options: ["up", "down"] },
        { name: "sensitivity", type: "select", options: ["public", "internal", "restricted"] },
        { name: "owner", type: "text" },
        { name: "targetJson", type: "json" }
      ]
    },
    {
      key: "snapshots",
      api: "/v1/north/snapshots",
      read: "north:snapshots:read",
      // Immutable in the API and machine-written by the rollup: no form here,
      // and no createdAt to sort by either.
      sort: "ts",
      order: "desc",
      filters: [{ name: "grain", options: ["day", "week", "month"] }],
      columns: [
        { name: "metricName", type: "json" },
        { name: "period", type: "text", sortable: true },
        { name: "grain", type: "text" },
        { name: "value", type: "measure", unitFrom: "unit", currencyFrom: "currency" },
        { name: "dimsHash", type: "text" },
        { name: "ts", type: "datetime", sortable: true }
      ]
    },
    {
      key: "briefings",
      api: "/v1/north/briefings",
      read: "north:briefings:read",
      // The narrative is drafted by the model; a human only asks for it and
      // approves it, which is exactly the two permissions below.
      create: "north:briefings:generate",
      update: "north:briefings:approve",
      sort: "date",
      order: "desc",
      filters: [
        { name: "audience", options: ["exec", "board", "investor"] },
        { name: "status", options: ["draft", "review", "published"] }
      ],
      // A briefing is its content: the narrative it points at, what it called
      // out, and the audit id that says which run wrote it. Approving one you
      // cannot read is not an approval.
      columns: [
        { name: "date", type: "text", sortable: true },
        { name: "audience", type: "text" },
        { name: "locale", type: "text" },
        { name: "status", type: "text", badge: true },
        { name: "narrativeRef", type: "text" },
        { name: "highlightsJson", type: "json" },
        { name: "anomaliesJson", type: "json" },
        { name: "generatedBy", type: "text" },
        { name: "aiAuditId", type: "text" },
        { name: "approvedBy", type: "text" },
        { name: "publishedAt", type: "datetime", sortable: true }
      ],
      fields: [
        { name: "date", type: "text", required: true },
        { name: "audience", type: "select", options: ["exec", "board", "investor"] },
        { name: "locale", type: "text" }
      ],
      editable: [{ name: "status", type: "select", options: ["draft", "review", "published"] }]
    },
    {
      key: "anomalies",
      api: "/v1/north/anomalies",
      read: "north:anomalies:read",
      // Detection writes these; a human can only triage one.
      update: "north:anomalies:assign",
      sort: "detectedAt",
      order: "desc",
      filters: [
        { name: "state", options: ["new", "explained", "action_created", "dismissed"] }
      ],
      columns: [
        { name: "metricKey", type: "text" },
        { name: "window", type: "text" },
        { name: "magnitude", type: "number" },
        { name: "expected", type: "number" },
        { name: "actual", type: "number" },
        // Detection's own reading of why it moved — the column the mockup calls
        // "NORTH's reading", and the reason a triager can act without opening it.
        { name: "driverAnalysisJson", type: "json" },
        { name: "state", type: "text", badge: true },
        { name: "detectedAt", type: "datetime", sortable: true }
      ],
      editable: [
        {
          name: "state",
          type: "select",
          options: ["new", "explained", "action_created", "dismissed"]
        },
        { name: "linkedActionRef", type: "text" },
        { name: "explainedBy", type: "text" }
      ]
    },
    {
      // The standing thresholds behind the anomalies tab: a rule is one row of
      // metric + operator + threshold, so it is a tab and not a builder.
      key: "alerts",
      api: "/v1/north/alert_rules",
      read: "north:alerts:read",
      create: "north:alerts:write",
      update: "north:alerts:write",
      remove: "north:alerts:write",
      sort: "metricKey",
      order: "asc",
      filters: [
        { name: "windowGrain", options: ["day", "week", "month"] },
        { name: "operator", options: ["gt", "gte", "lt", "lte", "eq"] }
      ],
      columns: [
        { name: "metricKey", type: "text", sortable: true },
        { name: "operator", type: "text" },
        { name: "thresholdValue", type: "number" },
        { name: "windowGrain", type: "text" },
        { name: "notifyChannelRef", type: "text" },
        { name: "enabled", type: "boolean" },
        { name: "updatedAt", type: "datetime", sortable: true }
      ],
      fields: [
        { name: "metricKey", type: "text", required: true },
        { name: "operator", type: "select", options: ["gt", "gte", "lt", "lte", "eq"], required: true },
        // Money metrics are stored in minor units (packages/db/src/schema/north.ts),
        // so the threshold is typed in the same units the snapshot carries.
        { name: "thresholdValue", type: "number", required: true, hintKey: "thresholdValue.hint" },
        { name: "windowGrain", type: "select", options: ["day", "week", "month"] },
        { name: "notifyChannelRef", type: "text" },
        { name: "enabled", type: "boolean" }
      ],
      editable: [
        { name: "operator", type: "select", options: ["gt", "gte", "lt", "lte", "eq"] },
        { name: "thresholdValue", type: "number", hintKey: "thresholdValue.hint" },
        { name: "windowGrain", type: "select", options: ["day", "week", "month"] },
        { name: "notifyChannelRef", type: "text" },
        { name: "enabled", type: "boolean" }
      ]
    },
    {
      key: "scenarios",
      api: "/v1/north/scenarios",
      read: "north:scenarios:read",
      create: "north:scenarios:run",
      update: "north:scenarios:run",
      columns: [
        { name: "question", type: "text" },
        { name: "author", type: "text" },
        { name: "modelRunRef", type: "text" },
        { name: "resultJson", type: "json" },
        { name: "createdAt", type: "datetime", sortable: true },
        { name: "updatedAt", type: "datetime", sortable: true }
      ],
      fields: [
        { name: "question", type: "textarea", required: true },
        { name: "assumptionsJson", type: "json", required: true },
        { name: "author", type: "text", required: true },
        { name: "sharedWithJson", type: "json" }
      ],
      // Re-running with new assumptions is the edit; the result is the model's
      // to write, never the form's.
      editable: [
        { name: "assumptionsJson", type: "json" },
        { name: "sharedWithJson", type: "json" }
      ]
    },
    {
      key: "boardpacks",
      api: "/v1/north/boardpacks",
      read: "north:boardpacks:read",
      // Generate only — a pack is regenerated, not patched, so the API offers
      // no update and this tab offers no edit form.
      create: "north:boardpacks:generate",
      sort: "period",
      order: "desc",
      filters: [{ name: "status", options: ["draft", "review", "final", "distributed"] }],
      columns: [
        { name: "title", type: "text" },
        { name: "period", type: "text", sortable: true },
        { name: "status", type: "text", badge: true },
        { name: "approvedBy", type: "text" },
        { name: "pdfFileId", type: "text" },
        { name: "xlsxFileId", type: "text" },
        // Who it went to and when — a distributed pack with no delivery record
        // cannot answer the only question anyone asks about one.
        { name: "distributionLogJson", type: "json" },
        { name: "updatedAt", type: "datetime", sortable: true }
      ],
      // docs/30 NORTH 5, rule 4: a person signs the pack off, then sends it.
      actions: [
        { intent: "approve", method: "POST", path: "/{id}/approve", labelKey: "boardpacks.approve", permission: "north:boardpacks:approve", confirm: true },
        {
          intent: "distribute",
          method: "POST",
          path: "/{id}/distribute",
          labelKey: "boardpacks.distribute",
          permission: "north:boardpacks:distribute",
          fields: [{ name: "recipients", type: "json", required: true }]
        }
      ],
      fields: [
        { name: "title", type: "text", required: true },
        { name: "period", type: "text", required: true },
        { name: "sectionsJson", type: "json", required: true }
      ]
    },
    {
      key: "decisions",
      api: "/v1/north/decisions",
      read: "north:decisions:read",
      create: "north:decisions:write",
      update: "north:decisions:write",
      remove: "north:decisions:write",
      sort: "reviewAt",
      order: "asc",
      filters: [{ name: "status", options: ["open", "reviewed", "reversed"] }],
      columns: [
        { name: "title", type: "text" },
        { name: "owner", type: "text" },
        { name: "chosen", type: "text" },
        { name: "status", type: "text", badge: true },
        { name: "reviewAt", type: "datetime", sortable: true },
        { name: "updatedAt", type: "datetime", sortable: true }
      ],
      fields: [
        { name: "title", type: "text", required: true },
        { name: "contextRef", type: "text" },
        { name: "optionsJson", type: "json" },
        { name: "owner", type: "text", required: true },
        { name: "reviewAt", type: "datetime" }
      ],
      editable: [
        { name: "chosen", type: "text" },
        { name: "status", type: "select", options: ["open", "reviewed", "reversed"] },
        { name: "owner", type: "text" },
        { name: "reviewAt", type: "datetime" },
        { name: "outcomeReviewJson", type: "json" }
      ]
    }
  ],
  // The screens NORTH is actually opened for. Reporting and dashboards live in
  // the analytics workspace and are linked, not rebuilt — one dashboard renderer
  // for the whole product (apps/web/app/routes/analytics-dashboard.tsx).
  links: [
    { href: "/north/brief", labelKey: "link.brief", permission: "north:briefings:read" },
    { href: "/north/explorer", labelKey: "link.explorer", permission: "north:snapshots:read" },
    { href: "/north/anomalies", labelKey: "link.anomalies", permission: "north:anomalies:read" },
    { href: "/north/alerts", labelKey: "link.alerts", permission: "north:alerts:read" },
    { href: "/north/whatif", labelKey: "link.whatif", permission: "north:scenarios:read" },
    { href: "/north/board", labelKey: "link.board", permission: "north:boardpacks:read" },
    { href: "/north/decisions", labelKey: "link.decisions", permission: "north:decisions:read" },
    { href: "/north/admin", labelKey: "link.admin", permission: "north:metrics:write" },
    { href: "/north/dev", labelKey: "link.dev", permission: "north:snapshots:run" },
    // ponytail: health / semantic / usage were
    // linked before their screens existed and shipped 404s into the nav. The
    // tabs below already list snapshots, scenarios and board packs; re-add a
    // link the day its bespoke screen lands (spec.routes.test.ts enforces it).
    { href: "/analytics/dashboards", labelKey: "link.dashboards", permission: "analytics:dashboards:read" },
    { href: "/analytics/reports", labelKey: "link.reports", permission: "analytics:reports:read" }
  ]
};
