import {
  Form,
  Link,
  useActionData,
  useLoaderData,
  useNavigation,
  useSearchParams,
  type ActionFunctionArgs,
  type LoaderFunctionArgs
} from "react-router";
import {
  AGENT_MARK,
  Badge,
  Button,
  Card,
  DateTime,
  EmptyState,
  EvidenceLink,
  Field,
  GuardrailNotice,
  Input,
  Ref,
  Select
} from "@lyra/ui";
import { api } from "../api.server";
import { humanise } from "../modules/spec";
import { cloudflare } from "../context";
import { Gate } from "./staff";
import { useNorthSessionData } from "./north-shell";
import {
  MetricValue,
  labelsFrom,
  chosen,
  metricName,
  narrative,
  num,
  parsed,
  pct,
  readable,
  refuse,
  refused,
  type ActionResult,
  type Anomaly,
  type Labels,
  type Metric,
  type Page
} from "./north-shared";

// The Brief (docs/25 north_brief): the narrative NORTH wrote from the ledger,
// the three numbers it leaned on, and the one anomaly nobody owns yet. A reading
// column, not a dashboard — the point is that an executive reads it end to end.
//
// Everything here is one of three real endpoints: the briefings resource, the
// anomalies resource, and POST /v1/north/briefings/generate (the narrator
// engine). No number on this screen is composed in the browser.

/* --------------------------------------------------------------- constants */

/** The exact permissions the API's own require_() calls name. */
export const PERM = {
  generate: "north:briefings:generate",
  approve: "north:briefings:approve",
  assign: "north:anomalies:assign"
} as const;

const RECENT = 7;
const AUDIENCES = ["exec", "board", "investor"] as const;

/* ------------------------------------------------------------------ labels */

const LABELS: Labels = {
  en: {
    title: "The Brief",
    kicker: "Narrated by NORTH from the live ledger",
    intro: "Every number traces to the snapshot it was generated from. Nothing here is published until a person says so.",
    print: "Print",
    "link.board": "Board pack",
    "link.whatif": "What-if",
    // The three audiences a briefing can be written for, and the three states it
    // can be in. Rendered directly as `l(brief.audience)` / `l(row.status)`,
    // so a missing key here shows the actor a raw enum.
    exec: "Executive",
    board: "Board",
    investor: "Investor",
    draft: "Draft",
    review: "In review",
    published: "Published",
    "brief.none.title": "No briefing has been written yet",
    "brief.none.body": "Asking for one runs the narrator over the metrics that have closed, and lands it here for review.",
    "brief.denied": "You do not have permission to read briefings. Ask a tenant administrator for NORTH briefing access.",
    "brief.audit": "How this was written",
    "brief.auditBody": "Generated by the NORTH narrator against the closed snapshots for this date. Numbers that could not be traced back to a snapshot keep the briefing in draft.",
    "brief.draft": "Numbers unverified",
    "brief.draftWhy": "At least one figure in this narrative could not be matched to a snapshot, so it stays a draft. Read it, but do not circulate it.",
    "highlights.title": "What moved most",
    "highlights.none": "No metric had a comparable prior period, so there is nothing to rank.",
    "anomaly.title": "Needs an owner",
    "anomaly.reason": "{metric} moved from {expected} to {actual} over {window}. Until someone owns it, nobody is looking.",
    "anomaly.owner": "Owner",
    "anomaly.ownerHint": "The person who will explain or act on it. Recorded against the anomaly.",
    "anomaly.assign": "Assign an owner",
    "anomaly.assigned": "Owner recorded.",
    "anomaly.open": "Open the anomaly",
    "publish.title": "Ready to publish",
    "publish.body": "Publishing marks this briefing as the one the audience read. It cannot be unsaid, only superseded.",
    "publish.submit": "Publish this briefing",
    "publish.done": "Briefing published.",
    "publish.pending": "Publishing was refused pending approval.",
    "generate.title": "Ask for a briefing",
    "generate.body": "The narrator reads the metrics that closed on or before this date. A date with no closed snapshot produces nothing to narrate.",
    "generate.date": "Date",
    "generate.audience": "Audience",
    "generate.submit": "Write the briefing",
    "generate.done": "Briefing written and waiting for review.",
    "recent.title": "Earlier briefings",
    "problem.bad_date": "A briefing needs a date in the form 2026-08-03.",
    "problem.missing_id": "That briefing could not be identified.",
    "problem.missing_owner": "Name the person who will own this anomaly.",
    "problem.bad_intent": "That form did not carry a recognised action."
  },
  ar: {
    title: "الموجز",
    kicker: "صياغة نورث من السجل الحي",
    intro: "كل رقم يعود إلى اللقطة التي وُلد منها. ولا شيء هنا يُنشر قبل أن يقرّه إنسان.",
    print: "طباعة",
    "link.board": "حزمة المجلس",
    "link.whatif": "ماذا لو",
    exec: "الإدارة التنفيذية",
    board: "مجلس الإدارة",
    investor: "المستثمرون",
    draft: "مسودة",
    review: "قيد المراجعة",
    published: "منشورة",
    "brief.none.title": "لم تُكتب أي إحاطة بعد",
    "brief.none.body": "طلب إحاطة يشغّل الراوي على المؤشرات المغلقة، ويضع النتيجة هنا للمراجعة.",
    "brief.denied": "لا تملك صلاحية قراءة الإحاطات. اطلب من مسؤول المؤسسة صلاحية إحاطات نورث.",
    "brief.audit": "كيف كُتب هذا",
    "brief.auditBody": "كتبه راوي نورث من اللقطات المغلقة لهذا التاريخ. أي رقم لا يمكن ربطه بلقطة يُبقي الإحاطة مسودة.",
    "brief.draft": "أرقام غير موثّقة",
    "brief.draftWhy": "رقم واحد على الأقل في هذا السرد لم يُطابق أي لقطة، لذلك يبقى مسودة. اقرأه ولا تعمّمه.",
    "highlights.title": "أكبر التحركات",
    "highlights.none": "لا يوجد مؤشر له فترة سابقة مماثلة، فلا شيء يُرتَّب.",
    "anomaly.title": "بحاجة إلى مسؤول",
    "anomaly.reason": "{metric} انتقل من {expected} إلى {actual} خلال {window}. وبلا مسؤول لا أحد يراقبه.",
    "anomaly.owner": "المسؤول",
    "anomaly.ownerHint": "الشخص الذي سيفسّره أو يتصرف بشأنه. يُسجَّل على الانحراف.",
    "anomaly.assign": "تعيين مسؤول",
    "anomaly.assigned": "تم تسجيل المسؤول.",
    "anomaly.open": "فتح الانحراف",
    "publish.title": "جاهزة للنشر",
    "publish.body": "النشر يثبّت هذه الإحاطة كالنسخة التي قرأها الجمهور. لا يمكن سحبها، بل استبدالها فقط.",
    "publish.submit": "نشر هذه الإحاطة",
    "publish.done": "تم نشر الإحاطة.",
    "publish.pending": "رُفض النشر بانتظار الموافقة.",
    "generate.title": "طلب إحاطة",
    "generate.body": "يقرأ الراوي المؤشرات المغلقة حتى هذا التاريخ. وتاريخ بلا لقطة مغلقة لا يعطي ما يُروى.",
    "generate.date": "التاريخ",
    "generate.audience": "الجمهور",
    "generate.submit": "اكتب الإحاطة",
    "generate.done": "كُتبت الإحاطة وهي في انتظار المراجعة.",
    "recent.title": "إحاطات سابقة",
    "problem.bad_date": "الإحاطة تحتاج تاريخًا بالشكل 2026-08-03.",
    "problem.missing_id": "لم يتم التعرف على هذه الإحاطة.",
    "problem.missing_owner": "سمِّ الشخص الذي سيتولى هذا الانحراف.",
    "problem.bad_intent": "لم يحمل النموذج إجراءً معروفًا."
  }
};

export function labelsIn(locale: string): (key: string, vars?: Record<string, string>) => string {
  return labelsFrom(LABELS, locale);
}

/* ------------------------------------------------------------------ shapes */

export interface Briefing {
  id: string;
  date: string;
  audience: string;
  locale: string;
  status: string;
  narrativeRef: string | null;
  // `*Json` columns: objects from the generic CRUD, text from a module route.
  // Read with parsed() (north-shared), never JSON.parse().
  highlightsJson: unknown;
  anomaliesJson: unknown;
  generatedBy: string | null;
  aiAuditId: string | null;
  approvedBy: string | null;
  publishedAt: number | null;
  createdAt: number;
}

interface Highlight {
  metricKey: string;
  period: string;
  value: number;
  deltaBps: number | null;
}

/* ----------------------------------------------------------------- helpers */

const DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * The narrative as paragraphs. Blank lines are the model's own breaks.
 *
 * Routed through `narrative()` because the column is not always prose: a row
 * seeded before f506bf7 holds a storage key no bucket was ever bound to hold.
 * Both call sites below read the same column, and both printed the key — the
 * `<h1>` headlined with it. Guarding here fixes them together.
 */
export function paragraphs(text: string | null | undefined): string[] {
  return (narrative(text) ?? "")
    .split(/\n\s*\n/)
    .map((part) => part.trim())
    .filter(Boolean);
}

/** The finding a hero can headline with, without running the whole paragraph on. */
export function firstSentence(paragraph: string | undefined): string | null {
  if (!paragraph) return null;
  return paragraph.split(/(?<=[.!?])\s+/)[0] ?? paragraph;
}

/**
 * The anomaly worth interrupting a read for: unowned, and the largest deviation
 * of those. Anything already explained or actioned is somebody's job already.
 */
export function unowned(rows: readonly Anomaly[] | null): Anomaly | null {
  const open = (rows ?? []).filter((row) => row.state === "new" && !row.explainedBy);
  if (!open.length) return null;
  return open.reduce((worst, row) => (Math.abs(row.magnitude) > Math.abs(worst.magnitude) ? row : worst));
}

/* ------------------------------------------------------------------ loader */

export async function loader({ request, context }: LoaderFunctionArgs) {
  const env = context.get(cloudflare).env;
  const opts = { env, request };
  const url = new URL(request.url);
  // ?asOf=<epoch-ms> replays this screen as of a past moment (Meridian's
  // replay mode) — an upper time bound on every query here, threaded through
  // to the API's pre-existing `to` param (apps/api/src/http.ts's ListQuery).
  const asOf = url.searchParams.get("asOf")?.trim();
  // A non-numeric ?asOf= is not a moment — replay stays off rather than
  // sending `&to=NaN` upstream.
  const to = asOf && Number.isFinite(Number(asOf)) ? `&to=${encodeURIComponent(asOf)}` : "";

  const [briefings, metrics, anomalies] = await Promise.all([
    readable(api<Page<Briefing>>(`/v1/north/briefings?sort=date&order=desc&limit=${RECENT}${to}`, opts)),
    // No `${to}`: this is the metric *definitions* catalogue, not a series.
    // Bounding it by the replay moment would hide definitions created since,
    // rather than replay their values — which is not what replay is for.
    readable(api<Page<Metric>>("/v1/north/metrics?limit=200", opts)),
    readable(
      api<Page<Anomaly>>(`/v1/north/anomalies?state=new&sort=detectedAt&order=desc&limit=10${to}`, opts)
    )
  ]);

  return {
    briefings: briefings?.data ?? null,
    metrics: metrics?.data ?? [],
    anomalies: anomalies?.data ?? [],
    // One key per load: a double-submitted generate is the same generate.
    idempotencyKey: crypto.randomUUID()
  };
}

/* ------------------------------------------------------------------ action */

export async function action({ request, context }: ActionFunctionArgs): Promise<ActionResult> {
  const env = context.get(cloudflare).env;
  const form = await request.formData();
  const intent = String(form.get("intent") ?? "");
  const key = String(form.get("idempotencyKey") ?? "");
  const opts = {
    env,
    request,
    method: "POST" as const,
    ...(key ? { headers: { "idempotency-key": key } } : {})
  };

  if (intent === "generate") {
    const date = String(form.get("date") ?? "").trim();
    if (!DATE.test(date)) return refuse("bad_date");
    const audience = String(form.get("audience") ?? "exec").trim() || "exec";
    try {
      await api("/v1/north/briefings/generate", { ...opts, body: { date, audience } });
    } catch (error) {
      return refused(error);
    }
    return { problem: null, saved: intent };
  }

  if (intent === "publish") {
    const id = String(form.get("id") ?? "").trim();
    if (!id) return refuse("missing_id");
    try {
      // Publishing is the consequential half of a briefing (rule 4): the API
      // gates it on north:briefings:approve and may hold it for approval, which
      // is surfaced rather than swallowed.
      await api(`/v1/north/briefings/${encodeURIComponent(id)}`, {
        ...opts,
        method: "PATCH",
        body: { status: "published" }
      });
    } catch (error) {
      return refused(error);
    }
    return { problem: null, saved: intent };
  }

  if (intent === "own-anomaly") {
    const id = String(form.get("id") ?? "").trim();
    const owner = String(form.get("owner") ?? "").trim();
    if (!id) return refuse("missing_id");
    if (!owner) return refuse("missing_owner");
    try {
      // `explainedBy` is the only person-shaped column on an anomaly, and
      // action_created is the state that says a human took it on.
      await api(`/v1/north/anomalies/${encodeURIComponent(id)}`, {
        ...opts,
        method: "PATCH",
        body: { state: "action_created", explainedBy: owner }
      });
    } catch (error) {
      return refused(error);
    }
    return { problem: null, saved: intent };
  }

  return refuse("bad_intent");
}

/* --------------------------------------------------------------- the screen */

export default function NorthBrief() {
  const loaded = useLoaderData<typeof loader>();
  const result = useActionData<typeof action>();
  const shell = useNorthSessionData();
  const navigation = useNavigation();
  const [params] = useSearchParams();

  const locale = shell?.locale ?? "en";
  const l = labelsIn(locale);
  const held = new Set(shell?.permissions ?? []);
  const busy = navigation.state !== "idle";

  const brief = chosen(loaded.briefings, params.get("id"), locale);
  const anomaly = unowned(loaded.anomalies);
  const byKey = new Map(loaded.metrics.map((metric) => [metric.key, metric]));
  const highlights = parsed<Highlight[]>(brief?.highlightsJson, []);

  const shown =
    result?.problem && result.problem.code !== "approval_required"
      ? {
          title: l(`problem.${result.problem.code ?? ""}`),
          status: result.problem.status,
          ...(result.problem.detail === undefined ? {} : { detail: result.problem.detail }),
          ...(result.problem.requestId === undefined ? {} : { requestId: result.problem.requestId })
        }
      : null;

  const value = (metricKey: string, raw: number) => {
    const metric = byKey.get(metricKey);
    return (
      <MetricValue
        value={raw}
        unit={metric?.unit ?? "count"}
        currency={metric?.currency ?? null}
        locale={locale}
      />
    );
  };
  const name = (metricKey: string) => {
    const metric = byKey.get(metricKey);
    // A briefing outlives the metric list it was written against, and the
    // anomaly copy reads "quote_latency_p95 moved from…" when it misses.
    return metric ? metricName(metric, locale) : humanise(metricKey);
  };

  return (
    <div className="flex flex-col gap-6">
      {/* A reading column, capped where prose stops being readable (docs/07). */}
      <div className="mx-auto flex w-full max-w-[var(--measure-prose)] flex-col gap-5">
        <header className="flex flex-wrap items-baseline justify-between gap-3">
          <span className="eyebrow">
            {l("title")}
            {brief ? ` · ${brief.date} · ${l(brief.audience)}` : null}
          </span>
          <div className="flex items-center gap-3">
            <Link
              to="/north/board"
              className="font-ui text-12 text-accent underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              {l("link.board")}
            </Link>
            <Link
              to="/north/whatif"
              className="font-ui text-12 text-accent underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              {l("link.whatif")}
            </Link>
            <Button variant="ghost" size="sm" onClick={() => window.print()}>
              {l("print")}
            </Button>
          </div>
        </header>

        <div className="flex flex-col gap-2">
          {/* The headline narrates the brief's own first finding rather than
              repeating the eyebrow's "The Brief" label — the sentence is
              the model's own text (paragraphs() splits on its own blank-line
              breaks), so it carries the same ✦ the kicker below already does. */}
          <h1 className="page-title">
            {firstSentence(paragraphs(brief?.narrativeRef).at(0)) ?? l("title")}
          </h1>
          {/* docs/15: one ✦ per AI artifact, and the "why" one interaction away. */}
          <p className="font-ui text-13 text-subtle">
            <EvidenceLink
              sourceLabel={l("brief.audit")}
              source={
                <p className="max-w-xs font-ui text-12 text-muted">
                  {l("brief.auditBody")}
                  {brief?.aiAuditId ? <Ref value={brief.aiAuditId} className="block text-12" /> : null}
                </p>
              }
            >
              <span aria-hidden="true">{AGENT_MARK}</span> {l("kicker")}
            </EvidenceLink>
          </p>
          <p className="font-ui text-12 text-subtle">{l("intro")}</p>
        </div>

        {shown ? <Gate problem={shown} l={l} /> : null}
        {result?.problem?.code === "approval_required" ? (
          <Gate problem={{ ...result.problem, status: result.problem.status }} l={l} />
        ) : null}
        {result?.saved === "publish" ? (
          <p role="status" className="font-ui text-13 text-success">
            {l("publish.done")}
          </p>
        ) : null}
        {result?.saved === "generate" ? (
          <p role="status" className="font-ui text-13 text-success">
            {l("generate.done")}
          </p>
        ) : null}

        {loaded.briefings === null ? (
          <p className="font-ui text-13 text-subtle">{l("brief.denied")}</p>
        ) : brief === null ? (
          <EmptyState title={l("brief.none.title")} body={l("brief.none.body")} />
        ) : (
          <article className="flex flex-col gap-4">
            {brief.status === "draft" ? (
              <GuardrailNotice tone="warning" title={l("brief.draft")} reason={l("brief.draftWhy")} />
            ) : null}

            {paragraphs(brief.narrativeRef).map((text, index) => (
              <p key={index} className="font-ui text-16 leading-relaxed text-muted">
                {text}
              </p>
            ))}

            {/* The anomaly interrupts the read on purpose: it is the one thing on
                the page that needs a person, and the ask is inline — never a modal
                (CLAUDE.md rule 11). */}
            {anomaly ? (
              <GuardrailNotice
                tone="warning"
                title={l("anomaly.title")}
                reason={l("anomaly.reason", {
                  metric: name(anomaly.metricKey),
                  expected: num(anomaly.expected, locale),
                  actual: num(anomaly.actual, locale),
                  window: anomaly.window
                })}
                action={
                  <div className="flex flex-col gap-2">
                    {held.has(PERM.assign) ? (
                      <Form method="post" className="flex flex-wrap items-end gap-2">
                        <input type="hidden" name="intent" value="own-anomaly" />
                        <input type="hidden" name="id" value={anomaly.id} />
                        <input type="hidden" name="idempotencyKey" value={loaded.idempotencyKey} />
                        <Field label={l("anomaly.owner")} hint={l("anomaly.ownerHint")}>
                          <Input name="owner" required size="sm" />
                        </Field>
                        <Button type="submit" variant="primary" size="sm" disabled={busy}>
                          {l("anomaly.assign")}
                        </Button>
                      </Form>
                    ) : null}
                    <Link
                      to={`/north/anomalies/${anomaly.id}`}
                      aria-label={`${l("anomaly.open")}: ${name(anomaly.metricKey)}`}
                      className="font-ui text-12 text-accent underline underline-offset-4"
                    >
                      {l("anomaly.open")}
                    </Link>
                  </div>
                }
              />
            ) : null}

            {result?.saved === "own-anomaly" ? (
              <p role="status" className="font-ui text-13 text-success">
                {l("anomaly.assigned")}
              </p>
            ) : null}

            <Card title={l("highlights.title")}>
              {highlights.length === 0 ? (
                <p className="font-ui text-13 text-subtle">{l("highlights.none")}</p>
              ) : (
                <ul className="flex flex-col divide-y divide-line">
                  {highlights.map((highlight) => (
                    <li
                      key={highlight.metricKey}
                      className="flex flex-wrap items-baseline justify-between gap-2 py-2 first:pt-0 last:pb-0"
                    >
                      <Link
                        to={`/north/explorer?metric=${encodeURIComponent(highlight.metricKey)}`}
                        className="font-ui text-13 text-accent underline underline-offset-4"
                      >
                        {name(highlight.metricKey)}
                      </Link>
                      <span className="flex items-baseline gap-3 font-ui text-13 text-text">
                        <span className="font-mono text-12 text-subtle">{highlight.period}</span>
                        {value(highlight.metricKey, highlight.value)}
                        {pct(highlight.deltaBps, locale) ? (
                          <Badge tone={(highlight.deltaBps ?? 0) >= 0 ? "success" : "danger"} size="sm">
                            {pct(highlight.deltaBps, locale)}
                          </Badge>
                        ) : null}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </Card>

            {brief.status !== "published" && held.has(PERM.approve) ? (
              <Card title={l("publish.title")} description={l("publish.body")}>
                <Form method="post" className="flex items-center gap-3">
                  <input type="hidden" name="intent" value="publish" />
                  <input type="hidden" name="id" value={brief.id} />
                  <input type="hidden" name="idempotencyKey" value={loaded.idempotencyKey} />
                  <Button type="submit" variant="primary" disabled={busy}>
                    {l("publish.submit")}
                  </Button>
                </Form>
              </Card>
            ) : null}
          </article>
        )}

        {held.has(PERM.generate) ? (
          <Card title={l("generate.title")} description={l("generate.body")}>
            <Form method="post" className="flex flex-wrap items-end gap-3">
              <input type="hidden" name="intent" value="generate" />
              <input type="hidden" name="idempotencyKey" value={loaded.idempotencyKey} />
              <Field label={l("generate.date")}>
                <Input type="date" name="date" required />
              </Field>
              <Field label={l("generate.audience")}>
                <Select
                  name="audience"
                  defaultValue="exec"
                  aria-label={l("generate.audience")}
                  options={AUDIENCES.map((audience) => ({ value: audience, label: l(audience) }))}
                />
              </Field>
              <Button type="submit" variant="primary" disabled={busy}>
                {l("generate.submit")}
              </Button>
            </Form>
          </Card>
        ) : null}

        {(loaded.briefings?.length ?? 0) > 1 ? (
          <Card title={l("recent.title")}>
            <ul className="flex flex-col divide-y divide-line">
              {loaded.briefings!.map((row) => (
                <li key={row.id} className="flex items-baseline justify-between gap-3 py-2 first:pt-0 last:pb-0">
                  <Link
                    to={`?id=${encodeURIComponent(row.id)}`}
                    className="font-ui text-13 text-accent underline underline-offset-4"
                  >
                    {row.date}
                  </Link>
                  <span className="flex items-baseline gap-2">
                    <Badge tone={row.status === "published" ? "success" : "neutral"} size="sm">
                      {l(row.status)}
                    </Badge>
                    <span className="font-ui text-12 text-subtle">
                      <DateTime value={row.createdAt} locale={locale} precision="day" />
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </Card>
        ) : null}
      </div>
    </div>
  );
}
