// Regenerates apps/api/src/engines/export/fonts/noto-naskh-arabic.ts, the font
// the PDF writer embeds for Arabic (ADR-0114). Run by hand, never at build time:
//
//   npm pack @fontsource/noto-naskh-arabic@5.3.0      # OFL-1.1
//   tar xzf fontsource-noto-naskh-arabic-5.3.0.tgz
//   pnpm exec tsx scripts/build-pdf-font.ts package/files/noto-naskh-arabic-arabic-400-normal.woff
//
// It unpacks the WOFF (zlib per table), keeps only the code points the shaper
// can emit — the Arabic block, the presentation forms in arabic.ts, space —
// and drops the tables the PDF never reads (GSUB, GPOS, GDEF, STAT, post,
// gasp). Glyph ids are left where they were. The licence travels with the
// font as a `/*!` legal comment, which the bundler keeps, so every deployed
// Worker carries the OFL text the licence requires (fonts/OFL.txt).

import { readFileSync, writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { PRESENTATION_FORMS } from "../apps/api/src/engines/export/arabic.js";
import { parseTrueType, subsetTrueType } from "../apps/api/src/engines/export/truetype.js";

const OUT = new URL("../apps/api/src/engines/export/fonts/noto-naskh-arabic.ts", import.meta.url);

function woffToSfnt(b: Buffer): Uint8Array {
  if (b.toString("latin1", 0, 4) !== "wOFF") throw new Error("not a WOFF 1.0 file");
  const flavor = b.readUInt32BE(4);
  const n = b.readUInt16BE(12);
  const tables: { tag: string; data: Buffer }[] = [];
  for (let i = 0; i < n; i++) {
    const o = 44 + i * 20;
    const off = b.readUInt32BE(o + 4);
    const comp = b.readUInt32BE(o + 8);
    const orig = b.readUInt32BE(o + 12);
    const raw = b.subarray(off, off + comp);
    tables.push({ tag: b.toString("latin1", o, o + 4), data: comp < orig ? inflateSync(raw) : raw });
  }
  tables.sort((a, c) => (a.tag < c.tag ? -1 : 1));
  const head = Buffer.alloc(12 + 16 * n);
  head.writeUInt32BE(flavor, 0);
  head.writeUInt16BE(n, 4);
  let at = head.length;
  const bodies: Buffer[] = [];
  tables.forEach((t, i) => {
    const o = 12 + i * 16;
    head.write(t.tag, o, "latin1");
    head.writeUInt32BE(at, o + 8);
    head.writeUInt32BE(t.data.length, o + 12);
    const pad = (4 - (t.data.length % 4)) % 4;
    bodies.push(t.data, Buffer.alloc(pad));
    at += t.data.length + pad;
  });
  return new Uint8Array(Buffer.concat([head, ...bodies]));
}

const src = process.argv[2];
if (!src) throw new Error("usage: tsx scripts/build-pdf-font.ts <noto-naskh-arabic-arabic-400-normal.woff>");
const font = parseTrueType(woffToSfnt(readFileSync(src)));

const wanted = new Set<number>([0x20, 0xa0, ...PRESENTATION_FORMS]);
for (let cp = 0x0600; cp <= 0x06ff; cp++) wanted.add(cp);
const cmap = new Map<number, number>();
for (const cp of wanted) {
  const g = font.cmap.get(cp);
  if (g) cmap.set(cp, g);
}
const missing = PRESENTATION_FORMS.filter((cp) => !cmap.has(cp));
if (missing.length) throw new Error(`font lacks presentation forms: ${missing.map((c) => c.toString(16)).join(" ")}`);

const bytes = subsetTrueType(font, cmap.values(), { keep: ["OS/2", "name"], cmap });
const b64 = Buffer.from(bytes).toString("base64");
const lines = b64.match(/.{1,120}/g) ?? [];
const licence = readFileSync(new URL("OFL.txt", OUT), "utf8").trimEnd();
if (licence.includes("*/")) throw new Error("OFL.txt cannot sit inside a block comment");

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-pdf-font.ts — do not edit. See ADR-0114.
//
// Noto Naskh Arabic Regular, Arabic subset, from @fontsource/noto-naskh-arabic
// 5.3.0. Copyright 2022 The Noto Project Authors
// (https://github.com/notofonts/arabic). Licensed under the SIL Open Font
// License, Version 1.1 — full text in ./OFL.txt beside this file. Reduced to
// the ${cmap.size} code points the PDF shaper emits; glyph outlines unchanged.
//
// ${bytes.length} bytes of TrueType, base64 so the module loads the same on
// Workers and Node with no file access at render time.

/*! Noto Naskh Arabic (subset) — @license OFL-1.1
${licence}
*/

export const NOTO_NASKH_ARABIC_TTF: string = [
${lines.map((l) => `  "${l}"`).join(",\n")}
].join("");
`
);
console.log(`wrote ${OUT.pathname}: ${cmap.size} code points, ${bytes.length} bytes TTF, ${b64.length} base64`);
